---
# spell-checker:ignore packit specfile copr epel
# https://packit.dev/docs/configuration/
# TODO(ssbarnea): Is there a way to template the package name in order to make
# it easier to sync this config between projects?
specfile_path: dist/subprocess-tee.spec
actions:
  create-archive:
    - sh -c "rm dist/*.tar.gz >/dev/null || true"
    - python3 -m build --sdist --outdir dist
    - sh -c "ls dist/subprocess_tee-*.tar.gz"
  get-current-version:
    - python3 -m setuptools_scm --strip-dev
  post-upstream-clone:
    - bash -c "rm -f *.src.rpm && rm -rf dist/*.*"
    - mkdir -p dist
    - bash -c 'sed -e "s/VERSION_PLACEHOLDER/$(python3 -m setuptools_scm --strip-dev)/" .config/subprocess-tee.spec > dist/subprocess-tee.spec'
srpm_build_deps:
  - python3-build
  - python3-setuptools_scm
  - python3-pytest
jobs:
  - job: copr_build
    trigger: pull_request
    branch: main
    targets:
      - fedora-rawhide-x86_64
      - fedora-rawhide-aarch64
      - fedora-latest-x86_64
      - fedora-latest-aarch64
      # Missing python3-build see https://bugzilla.redhat.com/show_bug.cgi?id=2129071
      # - centos-stream-9-aarch64
      # - centos-stream-9-x86_64
  - job: tests
    trigger: pull_request
    branch: main
    targets:
      - fedora-latest
      - fedora-rawhide
  # - job: propose_downstream
  #   trigger: release
  #   metadata:
  #     dist-git-branch: master
notifications:
  pull_request:
    successful_build: false
